trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python311:
      python.version: '3.11'

steps:
- powershell: Remove-Item -Recurse -Force $(Build.SourcesDirectory)/*
  displayName: 'Clean Workspace'
  condition: succeededOrFailed()
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
      python -m pip install --upgrade pip
      pip install -r $(Build.SourcesDirectory)/.devcontainer/requirements.txt
  displayName: 'Install dependencies'
  
- script: |
    ls
    dir
    python main.py
  displayName: 'Run program'