trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python311:
      python.version: '3.11'

variables:
  target_commit: 'f8168fe3'  # Replace with the desired commit hash or ID

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
      python -m pip install --upgrade pip
      pip install -r $(Build.SourcesDirectory)/.devcontainer/requirements.txt
  displayName: 'Install dependencies'
  
- script: |
    git checkout $(target_commit)
    python main.py
  displayName: 'Run Python script at specific commit'
